// Total snippets: 12
// -----------------------------------------
// Snippet #0 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _EMISSION _GLOSSYREFLECTIONS_OFF _METALLICGLOSSMAP _NORMALMAP _PARALLAXMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2 INSTANCING_ON
Builtin keywords used: DIRECTIONAL LIGHTPROBE_SH SHADOWS_SHADOWMASK DYNAMICLIGHTMAP_ON LIGHTMAP_ON LIGHTMAP_SHADOW_MIXING DIRLIGHTMAP_COMBINED SHADOWS_SCREEN VERTEXLIGHT_ON

8 keyword variants used in scene:

DIRECTIONAL
DIRECTIONAL LIGHTPROBE_SH
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN
DIRECTIONAL VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH VERTEXLIGHT_ON
DIRECTIONAL SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON


// -----------------------------------------
// Snippet #1 platforms ffffffff:
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2

1 keyword variants used in scene:

<no keywords defined>


// -----------------------------------------
// Snippet #2 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _METALLICGLOSSMAP _NORMALMAP _PARALLAXMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2
Builtin keywords used: POINT DIRECTIONAL SPOT POINT_COOKIE DIRECTIONAL_COOKIE SHADOWS_SHADOWMASK LIGHTMAP_SHADOW_MIXING SHADOWS_DEPTH SHADOWS_SOFT SHADOWS_SCREEN SHADOWS_CUBE

13 keyword variants used in scene:

POINT
DIRECTIONAL
SPOT
POINT_COOKIE
DIRECTIONAL_COOKIE
SHADOWS_DEPTH SPOT
SHADOWS_DEPTH SHADOWS_SOFT SPOT
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL_COOKIE SHADOWS_SCREEN
POINT SHADOWS_CUBE
POINT SHADOWS_CUBE SHADOWS_SOFT
POINT_COOKIE SHADOWS_CUBE
POINT_COOKIE SHADOWS_CUBE SHADOWS_SOFT


// -----------------------------------------
// Snippet #3 platforms ffffffff:
Keywords always included into build: INSTANCING_ON
Builtin keywords used: SHADOWS_DEPTH SHADOWS_CUBE

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #4 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _METALLICGLOSSMAP _PARALLAXMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A
Keywords always included into build: INSTANCING_ON
Builtin keywords used: SHADOWS_DEPTH SHADOWS_CUBE

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #5 platforms ffffffff:
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2 POINT SPOT

3 keyword variants used in scene:

<no keywords defined>
POINT
SPOT


// -----------------------------------------
// Snippet #6 platforms fffffbff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP _NORMALMAP _PARALLAXMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: INSTANCING_ON
Builtin keywords used: LIGHTPROBE_SH DYNAMICLIGHTMAP_ON SHADOWS_SHADOWMASK LIGHTMAP_ON DIRLIGHTMAP_COMBINED UNITY_HDR_ON

4 keyword variants used in scene:

<no keywords defined>
LIGHTPROBE_SH
UNITY_HDR_ON
LIGHTPROBE_SH UNITY_HDR_ON


// -----------------------------------------
// Snippet #7 platforms ffffffff:
Keywords stripped away when not used: EDITOR_VISUALIZATION _DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A

1 keyword variants used in scene:

<no keywords defined>


// -----------------------------------------
// Snippet #8 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _EMISSION _GLOSSYREFLECTIONS_OFF _METALLICGLOSSMAP _NORMALMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2
Builtin keywords used: DIRECTIONAL LIGHTPROBE_SH SHADOWS_SHADOWMASK DYNAMICLIGHTMAP_ON LIGHTMAP_ON LIGHTMAP_SHADOW_MIXING SHADOWS_SCREEN VERTEXLIGHT_ON

8 keyword variants used in scene:

DIRECTIONAL
DIRECTIONAL LIGHTPROBE_SH
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN
DIRECTIONAL VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH VERTEXLIGHT_ON
DIRECTIONAL SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON


// -----------------------------------------
// Snippet #9 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _METALLICGLOSSMAP _NORMALMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: FOG_LINEAR FOG_EXP FOG_EXP2
Builtin keywords used: POINT DIRECTIONAL SPOT POINT_COOKIE DIRECTIONAL_COOKIE SHADOWS_SHADOWMASK LIGHTMAP_SHADOW_MIXING SHADOWS_DEPTH SHADOWS_SCREEN SHADOWS_CUBE

10 keyword variants used in scene:

POINT
DIRECTIONAL
SPOT
POINT_COOKIE
DIRECTIONAL_COOKIE
SHADOWS_DEPTH SPOT
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL_COOKIE SHADOWS_SCREEN
POINT SHADOWS_CUBE
POINT_COOKIE SHADOWS_CUBE


// -----------------------------------------
// Snippet #10 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _METALLICGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A
Builtin keywords used: SHADOWS_DEPTH SHADOWS_CUBE

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #11 platforms ffffffff:
Keywords stripped away when not used: EDITOR_VISUALIZATION _DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A

1 keyword variants used in scene:

<no keywords defined>


